#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pass 3: Final cleanup of remaining Chinese.
Strategy:
1. For release note files: the duplicate Chinese em[...] paragraphs can be removed
   since the English/PT clean version is adjacent.
2. For all files: remove/replace remaining isolated Chinese characters.
"""
import os, re
from pathlib import Path

BASE = Path('D:/Tutorials/m-auto.online/vci-help')

# Single-character and short-fragment Chinese -> English fallback translations
# These are leftovers from partial replacements
SINGLE_EN = {
    '角': 'angle',
    '失败': 'failure',
    '模': 'module',
    '先': 'first',
    '补丁': 'patch',
    '处': 'at',
    '变体': 'variant',
    '升': 'upgrade',
    '律选': 'select all',
    '开': 'open',
    '边框框': 'panel',
    '选': 'select',
    '起刷': 'flash all',
    '勾': 'check',
    '另': 'another',
    '进度条': 'progress bar',
    '方': 'below',
    '有': 'available',
    '启': 'start',
    '了': '',
    '底': 'base',
    '编': 'code',
    '代': 'represents',
    '其': 'its',
    '跑': 'sports',
    '旅行': 'touring',
    '型跑': 'sports car',
    '超': 'super/ultra',
    '情况': 'case',
    '跳': 'jumper',
    '工具': 'tool',
    '机': 'engine/machine',
    '它有': 'it has',
    '数人似乎更喜欢': 'most seem to prefer',
    '想太': 'overthink',
    '数人': 'most people',
    '忽略它': 'ignore it',
    '综合': 'comprehensive',
    '手': 'manual',
    '图': 'figure',
    '它': 'it',
    '部件照片': 'component photos',
    '想': 'want',
    '整视频': 'full video',
    '我': 'I',
    '现两者': 'found neither',
    '什么': 'any',
    '属': 'belongs to',
    '目录': 'catalog',
    '解': 'decode',
    '器': 'tool/device',
    '起作': 'work',
    '器来帮助': 'decoder to help',
    '非常好解': 'really nice decode',
    '也': 'also',
    '所述': 'mentioned',
    '许': 'many',
    '汽': 'automotive',
    '原理': 'principle',
    '致相': 'roughly the same',
    '它非常直观': "it's very intuitive",
    '确保': 'ensure',
    '任务栏': 'taskbar',
    '火': 'ignition',
    '织': 'organize',
    '让': 'let',
    '建': 'create',
    '命名': 'name',
    '勾选': 'check/select',
    '变体': 'variant',
    '种': 'type',
    '仍旧': 'still',
    '几': 'several',
    '指': 'guided',
    '整合了更': 'integrates more',
    '统': 'unified',
    '友好交互': 'user-friendly',
    '相互参照': 'cross-reference',
    '设': 'coding',
    '货': 'van',
    '加快了': 'accelerated',
    '更': 'more',
    '给': 'to',
    '户': 'user',
    '总体': 'overall',
    '来说': 'speaking',
    '人员': 'technician',
    '改变均': 'all changes',
    '当': 'when',
    '网站': 'portal',
    '账': 'account',
    '再次': 'again',
    '央': 'central',
    '改': 'change',
    '入': 'introduced',
    '户名': 'username',
    '些': 'these',
    '意味着': 'means',
    '经': 'already',
    '每': 'each',
    '身份': 'identification',
    '获得': 'obtain',
    '及': 'and',
    '整容相': 'adjust accordingly',
    '两种': 'two types',
    '少': 'at least',
    '替': 'replace',
    '前': 'before',
    '步': 'sync',
    '警': 'warning',
    '以': 'to',
    '法': 'cannot',
    '克隆': 'clone',
    '法升': 'cannot upgrade',
    '有效': 'valid',
    '满足以': 'meet',
    '条件': 'conditions',
    '效': 'effective/invalid',
    '允许': 'allows',
    '户禁': 'user disable',
    '屏幕': 'screen',
    '延迟': 'delay',
    '语音': 'voice',
    '三种': 'three types',
    '电': 'electric',
    '铃': 'ring',
    '室': 'indoor',
    '循环记忆': 'circulation memory',
    '次': 'time',
    '擎': 'engine',
    '档拨片': 'gear paddle',
    '水平': 'horizontal',
    '员': 'person',
    '椅': 'seat',
    '残疾人解开': 'disabled seatbelt release',
    '乘客': 'passenger',
    '起': 'start',
    '处': 'at',
    '按图': 'follow diagram',
    '样': 'same',
    '够': 'able to',
    '实': 'live',
    '传': 'upload',
    '量值': 'measurement values',
    '总': 'bus/total',
    '非': 'non',
    '特定': 'specific',
    '客户': 'customer',
    '期': 'term',
    '简': 'brief',
    '锁定': 'lock',
    '页': 'page',
    '存储器': 'memory',
    '运动型': 'sport',
    '农业': 'agricultural',
    '球': 'global',
    '农林地': 'agricultural/forestry land',
    '农业机械': 'agricultural machinery',
    '机械': 'machinery',
    '好': 'good',
    '微': 'WeChat',
    '企业': 'company',
    '成': 'composed',
    '本文档': 'this document',
    '按照以': 'follow',
    '正常': 'normal',
    '看': 'see',
    '相当': 'equivalent',
    '相': 'same',
    '产生冲突': 'conflict',
    '联网': 'internet',
    '版权属': 'copyright belongs',
    '者': 'owner',
    '击': 'click',
    '持': 'continuously',
    '始终保持': 'always keep',
    '当某': 'when a',
    '条件': 'conditions',
    '异常': 'abnormal',
    '就': 'then',
    '拷贝': 'copy',
    '整': 'complete',
    '拷': 'copy',
    '让客户': 'ask customer',
    '按': 'press',
    '框': 'dialog',
    '听': 'hear',
    '项': 'item',
    '天': 'days',
    '影响': 'affect',
    '联系经销商': 'contact dealer',
    '申': 'apply',
    '专': 'dedicated',
    '切': 'switch',
    '智': 'smart',
    '配': 'allocate',
    '佳': 'best',
    '各': 'various',
    '保持': 'maintain',
    '世界': 'world',
    '替代': 'replace',
    '昂贵': 'expensive',
    '各种': 'various',
    '协': 'cooperative',
    '灵活易': 'flexible',
    '采': 'using',
    '防反插加固': 'anti-reverse reinforced',
    '稳定': 'stable',
    '型': 'type/model',
    '橡胶坚固': 'robust rubber',
    '满足四': 'meets four',
    '铝': 'aluminum',
    '光': 'CD/optical',
    '入': 'connect',
    '呼吸': 'breathing',
    '慢速': 'slow',
    '数': 'most',
    '紧凑': 'compact',
    '价': 'value',
    '制造商': 'manufacturer',
    '它': 'it',
    '搭载': 'equipped',
    '私有': 'proprietary',
    '通道': 'channel',
    '紧凑型': 'compact',
    '构': 'refactor',
    '断': 'interrupt',
    '前': 'before',
    '传输通道': 'transmission channel',
    '命令': 'command',
    '否定': 'negative',
    '答': 'response',
    '送': 'send',
    '触': 'trigger',
    '消息': 'message',
    '答处理': 'response handling',
    '住': 'stuck',
    '屏': 'shield/screen',
    '端统': 'unified',
    '日志': 'log',
    '割': 'split',
    '帧处理': 'frame processing',
    '准确': 'accurate',
    '帧': 'frame',
    '收': 'receive',
    '处理': 'processing',
    '限': 'limit',
    '含': 'include',
    '意外': 'unexpected',
    '收超': 'receive overflow',
    '读': 'read',
    '跳动': 'jitter',
    '移除': 'remove',
    '模拟': 'simulate',
    '件': 'file/component',
    '师版': 'engineer version',
    '丢失': 'lost',
    '死': 'deadlock',
    '正': 'correct',
    '确定': 'confirm',
    '帧': 'frame',
    '延': 'delay',
    '收乱序': 'receive out-of-order',
    '非': 'non',
    '获取': 'get',
    '存': 'store',
    '效': 'effective',
    '采集': 'collect',
    '回': 'return',
    '打断': 'interrupt',
    '待空闲处理': 'idle waiting processing',
    '初始': 'initial',
    '强制': 'force',
    '待空闲': 'wait idle',
    '软': 'soft',
    '崩溃': 'crash',
    '响': 'affect',
    '定': 'determine',
    '送失败': 'send failure',
    '师': 'engineer',
    '否': 'no/whether',
    '混合': 'mixed',
    '过滤器': 'filter',
    '空': 'empty',
    '节': 'segment',
    '芯片': 'chip',
    '减少': 'reduce',
    '设': 'set',
    '导': 'lead',
    '帧消息': 'frame message',
    '广播消息混合': 'broadcast message mixed',
    '广播消息过滤': 'broadcast message filter',
    '广播消息': 'broadcast message',
    '普通': 'normal',
    '帧消息混合': 'frame message mixed',
    '效率': 'efficiency',
    '校验': 'checksum',
    '逻辑顺序': 'logical order',
    '过滤': 'filter',
    '第': 'N-th',
    '止动装': 'stop device',
    '逻辑': 'logical',
    '符合': 'comply',
    '空闲': 'idle',
    '回掉处理丢失': 'callback processing lost',
    '通道扫描': 'channel scan',
    '阻止过滤器': 'blocking filter',
    '收海量': 'receive large amount',
    '缓冲队列溢出': 'buffer queue overflow',
    '死机': 'freeze/crash',
    '过滤器溢出处理': 'filter overflow handling',
    '送帧': 'send frame',
    '待': 'wait',
    '消息独立互': 'independent message',
    '影响': 'impact',
    '开启': 'enable',
    '收任': 'receive any',
    '慢速初始': 'slow initialization',
    '异步': 'asynchronous',
    '阻塞': 'blocking',
    '消息强制': 'force message',
    '消息过滤': 'message filter',
    '增': 'add',
    '日志缓冲': 'log buffer',
    '帧传输': 'frame transmission',
    '提升': 'improve',
    '任务切': 'task switch',
    '异常情况智': 'smart exception handling',
    '收': 'receive',
    '定义': 'define',
    '任务': 'task',
    '冲突': 'conflict',
    '戳微': 'timestamp',
    '溢出': 'overflow',
    '过滤器消息': 'filter message',
    '受': 'affected',
    '电顺序影响': 'power sequence affected',
    '报错': 'error report',
    '物理资源': 'physical resource',
    '互': 'mutual',
    '计数': 'count',
    '调': 'adjust',
    '栈': 'stack',
    '开启保持': 'enable keep',
    '送消息处理': 'send message processing',
    '波特率': 'baud rate',
    '电子': 'electronic',
    '防盗': 'immobilizer',
    '特': 'feature',
    '布局有': 'layout',
    '熟悉': 'familiar',
    '很': 'well',
    '段': 'period',
    '代工具': 'generation tool',
    '整': 'complete',
    '求': 'requirements',
    '成': 'switch to',
    '名字变': 'name changes',
    '了开': 'with development',
    '然': 'will',
    '报': 'report',
    '过来': 'recover',
    '扫描': 'scan',
    '迪尔': 'Deere',
    '由': 'freely',
    '农林地': 'agricultural land',
    '电子': 'electronic',
}

SINGLE_PT = {
    '角': 'ângulo',
    '失败': 'falha',
    '模': 'módulo',
    '先': 'primeiro',
    '补丁': 'patch',
    '处': 'em',
    '变体': 'variante',
    '升': 'actualizar',
    '律选': 'seleccionar tudo',
    '开': 'abrir',
    '边框框': 'painel',
    '选': 'seleccionar',
    '起刷': 'flash total',
    '勾': 'marcar',
    '另': 'outro',
    '进度条': 'barra de progresso',
    '方': 'abaixo',
    '有': 'disponível',
    '启': 'iniciar',
    '了': '',
    '底': 'base',
    '编': 'código',
    '代': 'representa',
    '其': 'seu',
    '跑': 'desportivo',
    '旅行': 'familiar',
    '型跑': 'desportivo',
    '超': 'super/ultra',
    '情况': 'caso',
    '跳': 'jumper',
    '工具': 'ferramenta',
    '机': 'motor/máquina',
    '它有': 'tem',
    '数人似乎更喜欢': 'maioria prefere',
    '想太': 'não pensar demais',
    '数人': 'maioria',
    '忽略它': 'ignorá-lo',
    '综合': 'completo',
    '手': 'manual',
    '图': 'figura',
    '它': 'ele',
    '部件照片': 'fotos de peças',
    '想': 'querer',
    '整视频': 'vídeo completo',
    '我': 'eu',
    '现两者': 'encontrou nenhum útil',
    '什么': 'qualquer',
    '属': 'pertence',
    '目录': 'catálogo',
    '解': 'decodificar',
    '器': 'ferramenta',
    '起作': 'funcionar',
    '器来帮助': 'decodificador para ajudar',
    '非常好解': 'bom decodificador',
    '也': 'também',
    '所述': 'mencionado',
    '许': 'muitos',
    '汽': 'automóvel',
    '原理': 'princípio',
    '致相': 'aproximadamente igual',
    '它非常直观': 'muito intuitivo',
    '确保': 'garantir',
    '任务栏': 'barra de tarefas',
    '火': 'ignição',
    '织': 'organizar',
    '让': 'deixar',
    '建': 'criar',
    '命名': 'nomear',
    '勾选': 'marcar',
    '种': 'tipo',
    '仍旧': 'ainda',
    '几': 'vários',
    '指': 'guiado',
    '整合了更': 'integra mais',
    '统': 'unificado',
    '友好交互': 'interface amigável',
    '相互参照': 'referência cruzada',
    '设': 'codificação',
    '货': 'carrinha',
    '加快了': 'acelerou',
    '更': 'mais',
    '给': 'para',
    '户': 'utilizador',
    '总体': 'geral',
    '来说': 'falando',
    '人员': 'técnico',
    '改变均': 'todas as alterações',
    '当': 'quando',
    '网站': 'portal',
    '账': 'conta',
    '再次': 'novamente',
    '央': 'central',
    '改': 'alterar',
    '入': 'introduzido',
    '户名': 'nome de utilizador',
    '些': 'estes',
    '意味着': 'significa',
    '经': 'já',
    '每': 'cada',
    '身份': 'identificação',
    '获得': 'obter',
    '及': 'e',
    '整容相': 'ajustar de acordo',
    '两种': 'dois tipos',
    '少': 'pelo menos',
    '替': 'substituir',
    '前': 'antes',
    '步': 'sincronizar',
    '警': 'aviso',
    '以': 'para',
    '法': 'não pode',
    '克隆': 'clone',
    '法升': 'não pode actualizar',
    '有效': 'válido',
    '满足以': 'cumprir',
    '条件': 'condições',
    '效': 'efectivo/inválido',
    '允许': 'permite',
    '户禁': 'utilizador desactivar',
    '屏幕': 'ecrã',
    '延迟': 'atraso',
    '语音': 'voz',
    '三种': 'três tipos',
    '电': 'eléctrico',
    '铃': 'toque',
    '室': 'interior',
    '循环记忆': 'memória de circulação',
    '次': 'vez',
    '擎': 'motor',
    '档拨片': 'patilha de mudança',
    '水平': 'horizontal',
    '员': 'pessoa',
    '椅': 'assento',
    '残疾人解开': 'cinto de segurança para deficientes',
    '乘客': 'passageiro',
    '起': 'arranque',
    '按图': 'seguir diagrama',
    '样': 'mesmo',
    '够': 'capaz',
    '实': 'real',
    '传': 'enviar',
    '量值': 'valores de medição',
    '总': 'barramento',
    '非': 'não',
    '特定': 'específico',
    '客户': 'cliente',
    '期': 'prazo',
    '简': 'breve',
    '锁定': 'bloquear',
    '页': 'página',
    '存储器': 'memória',
    '运动型': 'desportivo',
    '农业': 'agrícola',
    '球': 'global',
    '农林地': 'terra agrícola/florestal',
    '农业机械': 'maquinaria agrícola',
    '机械': 'maquinaria',
    '好': 'bom',
    '微': 'WeChat',
    '企业': 'empresa',
    '成': 'composto',
    '本文档': 'este documento',
    '按照以': 'seguir',
    '正常': 'normal',
    '看': 'ver',
    '相当': 'equivalente',
    '相': 'mesmo',
    '产生冲突': 'conflito',
    '联网': 'internet',
    '版权属': 'direitos de autor pertencem',
    '者': 'proprietário',
    '击': 'clique',
    '持': 'continuamente',
    '始终保持': 'manter sempre',
    '当某': 'quando um',
    '异常': 'anormal',
    '就': 'então',
    '拷贝': 'copiar',
    '整': 'completo',
    '拷': 'copiar',
    '让客户': 'pedir ao cliente',
    '按': 'pressionar',
    '框': 'caixa de diálogo',
    '听': 'ouvir',
    '项': 'item',
    '天': 'dias',
    '影响': 'afectar',
    '联系经销商': 'contactar revendedor',
    '申': 'solicitar',
    '专': 'dedicado',
    '切': 'comutar',
    '智': 'inteligente',
    '配': 'alocar',
    '佳': 'melhor',
    '各': 'vários',
    '保持': 'manter',
    '世界': 'mundial',
    '替代': 'substituir',
    '昂贵': 'caro',
    '各种': 'vários',
    '协': 'cooperativo',
    '灵活易': 'flexível',
    '采': 'utilizando',
    '防反插加固': 'anti-inversão reforçado',
    '稳定': 'estável',
    '型': 'tipo/modelo',
    '橡胶坚固': 'borracha robusta',
    '满足四': 'cumpre quatro',
    '铝': 'alumínio',
    '光': 'CD/óptico',
    '呼吸': 'respiração',
    '慢速': 'lento',
    '数': 'maioria',
    '紧凑': 'compacto',
    '价': 'valor',
    '制造商': 'fabricante',
    '搭载': 'equipado',
    '私有': 'proprietário',
    '通道': 'canal',
    '紧凑型': 'compacto',
    '构': 'refazer',
    '断': 'interrupção',
    '传输通道': 'canal de transmissão',
    '命令': 'comando',
    '否定': 'negativo',
    '答': 'resposta',
    '送': 'enviar',
    '触': 'acionar',
    '消息': 'mensagem',
    '答处理': 'tratamento de resposta',
    '住': 'bloqueado',
    '屏': 'ecrã',
    '端统': 'unificado',
    '日志': 'log',
    '割': 'dividir',
    '帧处理': 'processamento de frames',
    '准确': 'preciso',
    '帧': 'frame',
    '收': 'receber',
    '处理': 'processamento',
    '限': 'limite',
    '含': 'incluir',
    '意外': 'inesperado',
    '收超': 'recepção excessiva',
    '读': 'ler',
    '跳动': 'jitter',
    '移除': 'remover',
    '模拟': 'simular',
    '件': 'ficheiro/componente',
    '师版': 'versão engenheiro',
    '丢失': 'perdido',
    '死': 'bloqueio',
    '正': 'correcto',
    '确定': 'confirmar',
    '延': 'atraso',
    '收乱序': 'receber fora de ordem',
    '获取': 'obter',
    '存': 'armazenar',
    '效': 'efectivo',
    '采集': 'recolher',
    '回': 'retornar',
    '打断': 'interromper',
    '待空闲处理': 'processamento em espera inactiva',
    '初始': 'inicial',
    '强制': 'forçar',
    '待空闲': 'espera inactiva',
    '软': 'software',
    '崩溃': 'falha',
    '响': 'afectar',
    '定': 'determinar',
    '送失败': 'falha de envio',
    '师': 'engenheiro',
    '否': 'não/verificar',
    '混合': 'misto',
    '过滤器': 'filtro',
    '空': 'vazio',
    '节': 'segmento',
    '芯片': 'chip',
    '减少': 'reduzir',
    '设': 'definir',
    '导': 'conduzir',
    '帧消息': 'mensagem de frame',
    '广播消息混合': 'mensagem broadcast mista',
    '广播消息过滤': 'filtro de mensagem broadcast',
    '广播消息': 'mensagem broadcast',
    '普通': 'normal',
    '帧消息混合': 'mensagem de frame mista',
    '效率': 'eficiência',
    '校验': 'checksum',
    '逻辑顺序': 'ordem lógica',
    '过滤': 'filtrar',
    '第': 'N-ésimo',
    '止动装': 'dispositivo de paragem',
    '逻辑': 'lógico',
    '符合': 'cumprir',
    '空闲': 'inactivo',
    '回掉处理丢失': 'callback perdido',
    '通道扫描': 'scan de canal',
    '阻止过滤器': 'filtro de bloqueio',
    '收海量': 'receber grande quantidade',
    '缓冲队列溢出': 'overflow de buffer',
    '死机': 'bloqueio/crash',
    '过滤器溢出处理': 'tratamento de overflow de filtro',
    '送帧': 'enviar frame',
    '待': 'esperar',
    '消息独立互': 'mensagens independentes',
    '开启': 'activar',
    '收任': 'receber qualquer',
    '慢速初始': 'inicialização lenta',
    '异步': 'assíncrono',
    '阻塞': 'bloqueio',
    '消息强制': 'mensagem forçada',
    '消息过滤': 'filtro de mensagem',
    '增': 'adicionar',
    '日志缓冲': 'buffer de log',
    '帧传输': 'transmissão de frame',
    '提升': 'melhorar',
    '任务切': 'comutação de tarefas',
    '异常情况智': 'tratamento inteligente de excepção',
    '定义': 'definir',
    '任务': 'tarefa',
    '冲突': 'conflito',
    '戳微': 'timestamp',
    '溢出': 'overflow',
    '过滤器消息': 'mensagem de filtro',
    '受': 'afectado',
    '电顺序影响': 'afectado pela sequência de energia',
    '报错': 'relatório de erro',
    '物理资源': 'recurso físico',
    '互': 'mútuo',
    '计数': 'contar',
    '调': 'ajustar',
    '栈': 'stack',
    '开启保持': 'activar manter',
    '送消息处理': 'processamento de envio de mensagem',
    '波特率': 'velocidade de transmissão',
    '电子': 'electrónico',
    '防盗': 'imobilizador',
    '特': 'característica',
    '布局有': 'layout',
    '熟悉': 'familiar',
    '很': 'bem',
    '段': 'período',
    '代工具': 'ferramenta de geração',
    '求': 'requisitos',
    '名字变': 'nome muda',
    '了开': 'com desenvolvimento',
    '然': 'irá',
    '报': 'reportar',
    '过来': 'recuperar',
    '扫描': 'scan',
    '由': 'livremente',
    '电子': 'electrónico',
    '账户有': 'conta com',
    '放入': 'colocado em',
}

# Sort by length descending to avoid partial matches
PAIRS_EN = sorted(SINGLE_EN.items(), key=lambda x: -len(x[0]))
PAIRS_PT = sorted(SINGLE_PT.items(), key=lambda x: -len(x[0]))

def translate_pass3(text, pairs):
    for zh, target in pairs:
        text = text.replace(zh, target)
    return text

# Process all files
files = []
for root, dirs, fnames in os.walk(BASE):
    dirs[:] = [d for d in dirs if d not in ['_raw', 'assets']]
    for f in fnames:
        if f.endswith('.html'):
            files.append(Path(root) / f)

zh_pattern = re.compile(r'[\u4e00-\u9fff]')
changed = 0

for fp in files:
    is_pt = '\\pt\\' in str(fp) or '/pt/' in str(fp)
    try:
        content = fp.read_text(encoding='utf-8-sig')
    except Exception:
        continue
    if not zh_pattern.search(content):
        continue
    original = content
    if is_pt:
        content = translate_pass3(content, PAIRS_PT)
    else:
        content = translate_pass3(content, PAIRS_EN)
    if content != original:
        fp.write_text(content, encoding='utf-8')
        changed += 1

print(f'Pass 3: {changed} files updated')

# Final scan
remaining = []
for fp in files:
    try:
        content = fp.read_text(encoding='utf-8-sig')
        matches = re.findall(r'[\u4e00-\u9fff]+', content)
        if matches:
            remaining.append((str(fp).replace(str(BASE)+'\\','').replace(str(BASE)+'/',''), list(dict.fromkeys(matches))))
    except: pass

with open(str(BASE / '_remaining_chinese_pass3.txt'), 'w', encoding='utf-8') as out:
    out.write(f'Files still with Chinese after pass 3: {len(remaining)}\n\n')
    for fp, chars in remaining:
        out.write(f'{fp}\n')
        for c in chars:
            out.write(f'  {c}\n')
        out.write('\n')

print(f'After pass 3: {len(remaining)} files still have Chinese')
