#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Second pass: translate remaining Chinese strings in vci-help HTML files.
"""
import os, re
from pathlib import Path

BASE = Path('D:/Tutorials/m-auto.online/vci-help')

# Additional Chinese -> translation pairs (sorted longest first in processing)
# PT and EN share most of these since the text is already partially translated
# These are generic technical terms appearing in mixed-language sentences

ZH2_EN = [
    # From drive-update.html
    ('通用', 'GM'),
    ('本田', 'Honda'),
    # From vw.html
    ('电控', 'electronic control'),
    ('中读取故障码', 'fault code read from'),
    ('显示方向盘', 'steering wheel display'),
    ('置传感器', 'position sensor'),
    ('信', 'signal'),
    ('可靠', 'reliable'),
    ('属偶发性故障', 'intermittent fault'),
    ('方向盘', 'steering wheel'),
    ('角度传感器', 'angle sensor'),
    ('电压', 'voltage'),
    ('线故障', 'wire fault'),
    ('故障码', 'fault code'),
    ('由蓄电池所至', 'caused by battery'),
    ('没有损坏', 'undamaged'),
    ('方向盘角度传感器', 'steering angle sensor'),
    ('校零', 'zero calibration'),
    ('编码', 'coding'),
    ('利用', 'use'),
    ('自', 'self'),
    ('基本设定', 'basic settings'),
    ('具体', 'specific'),
    ('下', 'below'),
    ('启动', 'start'),
    ('方向盘向右', 'turn steering wheel right'),
    ('再向左', 'then left'),
    ('停', 'stop'),
    ('中', 'center'),
    ('刹车', 'brake'),
    ('读码', 'read codes'),
    ('清除故障码', 'clear fault codes'),
    ('设置', 'settings'),
    ('码', 'code'),
    ('同', 'same'),
    ('码可能', 'code may be'),
    ('正确则显示', 'correct if shown'),
    ('登录', 'login'),
    ('登录码', 'login code'),
    ('显示', 'display'),
    ('登录码失败', 'login code failed'),
    ('主', 'main'),
    ('基本调整', 'basic adjustment'),
    ('退出', 'exit'),
    ('某些', 'some'),
    ('上', 'above'),
    ('用', 'use'),
    ('代替了正确', 'replaced correct'),
    ('制动', 'brake'),
    ('排气操作', 'bleeding operation'),
    ('模组编码', 'module coding'),
    # From benz/205-doip-test.html
    ('要', 'need'),
    ('才能', 'in order to'),
    ('线', 'line/cable'),
    ('操纵', 'operate'),
    ('检测', 'detect'),
    ('图标', 'icon'),
    # From benz/211-zgw.html
    ('此', 'this'),
    ('必须先用补丁破解', 'must first patch/crack'),
    ('还要', 'also need to'),
    ('虚拟光驱加载', 'mount with virtual drive'),
    ('资料', 'data'),
    ('一般', 'usually'),
    ('会', 'will'),
    ('识别', 'recognize'),
    ('模块', 'module'),
    ('此处', 'here'),
    ('硬盘', 'hard drive'),
    ('比', 'than'),
    ('成功', 'successful'),
    # From benz/index.html
    ('变体编码', 'variant coding'),
    ('工业', 'industrial'),
    ('组', 'group'),
    # From benz/me97-dts.html
    ('快速', 'quickly'),
    ('连上电脑', 'connect to computer'),
    ('查看', 'check'),
    ('否最', 'if latest'),
    ('否正常', 'if normal'),
    ('一', 'one'),
    ('提示升级一律选', 'always select upgrade when prompted'),
    ('点', 'click'),
    ('车扫描', 'vehicle scan'),
    ('扫描完', 'scan complete'),
    ('点开', 'click open'),
    ('右边框框内查看', 'check in right panel'),
    ('零件', 'parts'),
    ('准备好', 'ready'),
    ('有些', 'some'),
    ('盘', 'disk'),
    ('夹内', 'in folder'),
    ('没有话得', 'if not available, get from'),
    ('官方服务器', 'official server'),
    ('应', 'should'),
    ('选一起刷', 'select all to flash'),
    ('勾上所有', 'check all'),
    ('过程中', 'during'),
    ('另一', 'another'),
    ('都刷完', 'all flashed'),
    ('进度条下方会有提示', 'progress bar shows completion'),
    # From benz/model-list.html
    ('第二代', 'second generation'),
    ('启用了', 'enabled'),
    ('底盘编', 'chassis code'),
    ('规则', 'rule'),
    ('它规定所有', 'it specifies all'),
    ('底盘代', 'chassis designation'),
    ('都以字母加三', 'all use letter plus three'),
    ('数字来表示', 'digits'),
    ('其中', 'where'),
    ('代表', 'represents'),
    ('门车', 'door car'),
    ('代表跑车', 'represents sports car'),
    ('代表旅行车', 'represents estate'),
    ('代表越野车', 'represents SUV'),
    ('级', 'class'),
    ('小型单厢车', 'small hatchback'),
    ('小型', 'compact'),
    ('中级', 'mid-size'),
    ('高级', 'premium'),
    ('越野车', 'SUV'),
    ('多', 'multi'),
    ('厢式车', 'van'),
    ('小型跑车', 'small sports car'),
    ('中型跑车', 'mid sports car'),
    ('高级跑车', 'premium sports car'),
    ('超级跑车', 'super sports car'),
    ('底盘列表', 'chassis list'),
    ('款', 'model'),
    # From benz/om906-diag.html
    ('一款', 'a'),
    ('升直列', 'L inline'),
    ('缸直列六缸顶置凸轮轴柴油', 'cylinder DOHC diesel'),
    ('它于', 'it was'),
    ('推出', 'launched'),
    ('天然气', 'natural gas'),
    ('座', 'seat'),
    ('此款', 'this model'),
    ('圆形', 'round'),
    ('实际', 'actual'),
    ('引', 'lead'),
    ('没有', 'without'),
    ('接头情况下可以', 'connector can'),
    ('线跳线', 'wire jumper'),
    ('配置', 'configure'),
    ('由于', 'because'),
    ('需要检测', 'need to detect'),
    ('还需要', 'also need'),
    ('此配置工具配置', 'configure with this tool'),
    ('配置工具', 'configuration tool'),
    ('工业机组', 'industrial engine'),
    ('界面', 'interface'),
    ('提示', 'prompt'),
    ('插针', 'pin'),
    ('头', 'connector'),
    ('请配置', 'please configure'),
    ('结果', 'result'),
    # From benz/vs30 - remaining Chinese
    ('您无需担心细节', "you don't need to worry about details"),
    ('但主要需要考虑', 'but the main thing to consider'),
    ('它有多', 'it comes in different'),
    ('您应', 'you should'),
    ('考虑', 'consider'),
    ('大多数人似乎更喜欢', 'most people seem to prefer'),
    ('但', 'but'),
    ('我看来', 'in my opinion'),
    ('想太多', 'overthink it'),
    ('大多数人可能都会忽略它', 'most people can probably ignore it'),
    ('更详细概述请访问', 'for a longer overview:'),
    ('一综合性维修手册', 'a comprehensive repair manual and'),
    ('库', 'database'),
    ('它提供有关维修', 'it provides information on repair'),
    ('技术服务', 'technical service'),
    ('告', 'bulletins'),
    ('接线图', 'wiring diagrams'),
    ('它会向您显示您货车所有小部件照片', "it shows photos of all van components"),
    ('您想要完整视频', 'if you want full videos'),
    ('动画来了解', 'and animations of'),
    ('何操作', 'how to do stuff'),
    ('则可以', 'you can use'),
    ('我发现两者都没什么用', "I haven't found much use for either"),
    ('属于同一', 'part of the same'),
    ('一', 'an'),
    ('线零件目录', 'online parts catalog'),
    ('内置有', 'has built-in'),
    ('解码器', 'VIN decoder'),
    ('于较', 'for newer'),
    ('货车来说', 'vans'),
    ('这似乎', "that doesn't seem to"),
    ('起作用', 'work'),
    ('因', 'because'),
    ('它们', 'they are'),
    ('最', 'latest'),
    ('我货车', 'my van'),
    ('配备', 'equipped with'),
    ('变速箱', 'transmission'),
    ('这类', 'that type of'),
    ('中找', 'to find'),
    ('您货车', 'your van'),
    ('您需要', 'if you need'),
    ('解码器来帮助您', 'decoder to help'),
    ('这', 'this'),
    ('一非常好解码器', 'a really nice decoder'),
    ('这也可以', 'this one is okay too'),
    ('概述', 'overview'),
    ('任何提供', 'any providing'),
    ('端口', 'port'),
    ('您', 'you'),
    ('上所述', 'mentioned above'),
    ('许多', 'many'),
    ('都可以实现这一点', 'can achieve this'),
    ('这里我', 'here I will'),
    ('重点介绍', 'focus on'),
    ('非常强大小东西', 'powerful little thing'),
    ('适', 'works with'),
    ('同汽车', 'different car'),
    ('所有主要', 'all the main'),
    ('包括', 'including'),
    ('它还适', 'it also works with'),
    ('复用器', 'multiplexer'),
    ('可以', 'can'),
    ('提供', 'provided'),
    ('您计算机', 'your computer'),
    ('所有', 'all'),
    ('原理大致相同', 'work about the same'),
    ('了保持', 'to maintain'),
    ('我更喜欢', 'I prefer'),
    ('书', 'instructions'),
    ('但它非常直观', "but it's pretty intuitive"),
    ('其插入', 'plug it in'),
    ('计算机', 'computer'),
    ('其余操作', 'the rest'),
    ('编码主要', 'coding main'),
    ('已预装', 'pre-installed'),
    ('何', 'how'),
    ('管理器', 'Manager'),
    ('此工具', 'this tool'),
    ('主要', 'main'),
    ('请', 'please'),
    ('您无需', "you don't need"),
    ('您货车即可', 'your van'),
    ('下图', 'image below'),
    ('低', 'low'),
    ('未', 'without'),
    ('情况下', 'situation'),
    ('笔记本电脑', 'laptop'),
    ('则会弹出', 'will pop up'),
    ('之前', 'before'),
    ('请确保所有', 'make sure all'),
    ('都已', 'are all'),
    ('处于活动', 'are active'),
    ('请查看任务栏', 'check taskbar'),
    ('开关已', 'switch is'),
    ('已启动', 'started'),
    ('已', 'already'),
    ('它应', 'it should'),
    ('读取您', 'read your'),
    ('稍', 'wait a'),
    ('片刻', 'moment'),
    ('都', 'all'),
    ('正确', 'correct'),
    ('应', 'should'),
    ('会读取您', 'will read your'),
    ('点火', 'ignition'),
    ('中组织', 'organize in'),
    ('首先', 'first'),
    ('让我们启动', "let's start"),
    ('中创建', 'create in'),
    ('区', 'zone'),
    ('区命名', 'zone name'),
    ('检查', 'check'),
    ('卡中', 'in card'),
    ('还要确保', 'also make sure'),
    ('已被勾选', 'is checked'),
    # benz/xentry-das-guide.html
    ('仅能', 'can only'),
    ('以及之', 'and before'),
    ('于', 'on'),
    ('辆', 'vehicle'),
    ('这种', 'this type of'),
    ('换', 'replace'),
    ('之', 'of'),
    ('实现了', 'achieved'),
    ('仍旧适', 'still works with'),
    ('包含', 'includes'),
    ('下几', 'following'),
    ('指引检测', 'guided diagnostics'),
    ('视图', 'view'),
    ('整合了更多', 'integrates more'),
    ('统一', 'unified'),
    ('友好交互界面', 'user-friendly interface'),
    ('其他应用相互参照', 'cross-reference with other applications'),
    ('规范化故障症状来', 'standardized fault symptoms for'),
    ('改进评估', 'improved assessment'),
    ('线操作指引', 'online operation guide'),
    ('让你能', 'allowing you to'),
    ('设码', 'coding'),
    ('改装', 'modification'),
    ('加装', 'add-on'),
    ('配置码', 'configuration code'),
    ('以及', 'and also'),
    ('厢式货车', 'van'),
    ('于货车', 'for vans'),
    ('我们', 'we'),
    ('线操作', 'online operations'),
    ('此', 'this'),
    ('加快了维修车间更换', 'accelerated workshop replacement'),
    ('取得', 'obtain'),
    ('速度', 'speed'),
    ('给用户', 'to users'),
    ('来附加值', 'added value'),
    ('此过程', 'this process'),
    ('完', 'complete'),
    ('集成', 'integrated'),
    ('总体上来说', 'overall'),
    ('运行中', 'running'),
    ('几乎', 'almost'),
    ('需要维修人员', 'requires technician'),
    ('手动操作', 'manual operation'),
    ('干预', 'intervention'),
    ('运行', 'run'),
    ('设码以及', 'coding and'),
    ('每次', 'each time'),
    ('话', 'means'),
    ('所有改变均会被', 'all changes are saved'),
    ('至', 'to'),
    ('卡中', 'in card'),
    ('单次登陆操作', 'single login'),
    ('当用户', 'when user'),
    ('售', 'after-sales'),
    ('服务应用网站登陆账', 'service portal login'),
    ('续操作', 'subsequent operations'),
    ('需要再次登陆中央', 'require central re-login'),
    ('自', 'since'),
    ('月起', 'month'),
    ('用户权限', 'user permissions'),
    ('随着', 'with'),
    ('级改款', 'class facelift'),
    ('级引入', 'class introduction'),
    ('一种', 'a'),
    ('安', 'security'),
    ('概念正', 'concept being'),
    ('引入', 'introduced'),
    ('这也', 'this also'),
    ('产生重大影响', 'has major impact'),
    ('月', 'month'),
    ('发布', 'released'),
    ('当访问', 'when accessing'),
    ('出现', 'appears'),
    ('性化用户名', 'personalized username'),
    ('就无法', 'cannot'),
    ('这些', 'these'),
    ('这意味着', 'this means'),
    ('未经', 'without'),
    ('访问', 'access'),
    ('能再', 'can no longer'),
    ('维修', 'repair'),
    ('每一用户都必须经过一身份识别过程', 'each user must go through an identification process'),
    ('才能获得', 'to obtain'),
    ('续', 'continued'),
    ('整容相应用户权限', 'adjust user permissions accordingly'),
    ('可用两种用户权限', 'two user permission levels available'),
    ('读取', 'read'),
    ('清除故障记忆', 'clear fault memory'),
    ('权限', 'permissions'),
    ('应于', 'applies to'),
    ('无法再', 'can no longer'),
    ('您至少需要一', 'you need at least one'),
    ('可以实现完', 'can achieve full'),
    ('替换', 'replace'),
    ('前请确保', 'before ensure'),
    ('已经', 'already'),
    ('过程', 'process'),
    ('同步', 'synchronize'),
    ('必须', 'must'),
    ('匹配', 'match'),
    ('才可正常', 'to work properly'),
    ('当您手动', 'when you manually'),
    ('导致', 'causes'),
    ('则会出现', 'will appear'),
    ('下警告提示', 'warning prompt'),
    ('重', 'again'),
    ('也可运行', 'can also run'),
    ('手动', 'manually'),
    ('无', 'no'),
    ('非法', 'illegal'),
    ('以下情况下可能无法', 'may not work in following cases'),
    ('未升级至', 'not upgraded to'),
    ('非法克隆', 'illegal clone'),
    ('无法升级', 'cannot upgrade'),
    ('没有有效', 'no valid'),
    ('满足以上条件', 'meet above conditions'),
    ('显示无效', 'shows invalid'),
    # bmw/esys-guide.html
    ('发行', 'release'),
    ('上编码', 'coding on'),
    ('应用', 'application'),
    ('允许用户禁用', 'allows users to disable'),
    ('激活其', 'activate'),
    ('以下', 'following'),
    ('其中一些可以', 'some of which can be'),
    ('激活', 'activate'),
    ('禁用', 'disable'),
    ('锁定解锁声音', 'lock/unlock sound'),
    ('驾驶导航', 'driving navigation'),
    ('驾驶', 'driving'),
    ('观看', 'watching'),
    ('输出', 'output'),
    ('扭矩计', 'torque meter'),
    ('屏幕大屏幕启动延迟', 'large screen startup delay'),
    ('语音识别', 'voice recognition'),
    ('设置三种', 'set three types of'),
    ('电话铃声', 'ringtone'),
    ('地址', 'address'),
    ('空调', 'air conditioning'),
    ('室内循环记忆最', 'interior circulation memory'),
    ('一次引擎', 'engine start'),
    ('柱式电动', 'column electric'),
    ('挡板按钮', 'flap button'),
    ('遥控钥匙', 'remote key'),
    ('挡板', 'flap'),
    ('换档拨片', 'gear paddle'),
    ('小屏幕', 'small screen'),
    ('大屏幕显示', 'large screen display'),
    ('垂直', 'vertical'),
    ('水平显示', 'horizontal display'),
    ('驾驶员座椅', 'driver seat'),
    ('置', 'position'),
    ('残疾人解开安', 'disabled person seatbelt release'),
    ('语音提示', 'voice prompt'),
    ('乘客座', 'passenger seat'),
    ('行驶', 'driving'),
    ('交叉口', 'intersection'),
    ('远光灯', 'high beam'),
    ('控制', 'control'),
    ('天使眼睛', 'angel eyes'),
    ('起停', 'start/stop'),
    ('情况下处于', 'under conditions'),
    ('间同步', 'synchronize'),
    ('盖', 'cover'),
    ('来操作工程师', 'to operate engineer mode'),
    ('连上电脑', 'connect to computer'),
    ('首先查看', 'first check'),
    ('否最', 'if latest'),
    ('开关', 'switch'),
    ('就能读出', 'can read out'),
    ('示', 'shown'),
    ('直接', 'directly'),
    ('确定好', 'confirm'),
    ('按图示操作', 'follow diagram'),
    ('编码也', 'coding also'),
    ('这样读取', 'read this way'),
    ('超级远程', 'hyper remote'),
    ('连', 'connect'),
    # bmw/index.html
    ('介绍', 'introduction'),
    # bmw/inpa-guide.html
    ('能够读取', 'able to read'),
    ('清除所有模块', 'clear all modules'),
    ('代码', 'codes'),
    ('重置调整', 'reset adjustments'),
    ('查看实', 'view live'),
    ('所需只', 'requires only'),
    ('工程', 'engineering'),
    ('生产', 'production'),
    ('售', 'after-sales'),
    ('案例', 'cases'),
    ('清除', 'clear'),
    ('上传', 'upload'),
    ('读取测量值', 'read measurement values'),
    ('输出控制', 'output control'),
    ('单', 'single'),
    ('变量校准', 'variable calibration'),
    ('总线', 'bus'),
    ('仿真', 'simulation'),
    ('车载', 'on-board'),
    ('非车载集成', 'non-integrated'),
    ('特定于客户', 'customer-specific'),
    ('广泛', 'widely'),
    ('长期应用', 'long-term application'),
    ('语言', 'language'),
    ('英语', 'English'),
    ('德语', 'German'),
    ('例', 'example'),
    ('简单介绍', 'brief introduction'),
    ('连上', 'connect'),
    ('首先要锁定', 'first lock'),
    ('有两种', 'there are two types of'),
    ('主页', 'home page'),
    ('所需', 'required'),
    ('即可', 'then'),
    ('故障码存储器', 'fault code memory'),
    ('读存储器', 'read memory'),
    ('屏幕截图', 'screenshot'),
    ('结束', 'end'),
    # bmw/model-list.html
    ('运动型多', 'sport multi-purpose'),
    ('车', 'vehicle'),
    ('旅行车', 'touring'),
    # gm/gds2-device-not-detected.html
    ('专业版', 'Professional edition'),
    ('非家庭版', 'non-Home edition'),
    ('保证', 'ensure'),
    ('账户有管理员权限', 'account has administrator rights'),
    ('运行库没有被正确', 'runtime library not correctly'),
    ('运行库', 'runtime library'),
    ('已放入', 'already placed in'),
    # honda/hds-guide.html
    ('以及电子', 'and electronic'),
    ('重', 're-'),
    ('包括但', 'including but'),
    ('限于', 'not limited to'),
    ('提供访问所有本田', 'provides access to all Honda'),
    ('访问防盗', 'access immobilizer'),
    ('需要安', 'requires'),
    ('专业人员', 'professional'),
    ('订阅', 'subscription'),
    ('安', 'install'),
    ('向', 'towards'),
    ('册', 'register'),
    ('充满了', 'full of'),
    ('特点', 'features'),
    ('给用户一布局有点熟悉传统', 'gives users a familiar traditional layout'),
    ('很长一段', 'a long'),
    ('间里很好地', 'period well'),
    ('了我们', 'served us'),
    ('经过', 'after'),
    ('实践', 'practice'),
    ('一代工具被设计', 'previous generation tool was designed'),
    ('一代', 'generation'),
    ('所有完整', 'all complete'),
    ('变化', 'changes'),
    ('要求', 'requirements'),
    # porsche/pt3g-engineer.html
    ('内', 'within'),
    ('要操作车款', 'for older models'),
    ('分', 'divided into'),
    ('老款', 'older'),
    ('车款', 'model'),
    ('里', 'in'),
    ('即可换成工程师', 'switch to engineer mode'),
    ('同样操作选', 'same operation to select'),
    ('换回', 'switch back'),
    ('控制模块', 'control module'),
    ('会发现', 'you will find'),
    ('控制模块名字变', 'control module name changes to'),
    ('德文', 'German'),
    ('多了开发', 'with development'),
    ('可', 'can'),
    ('工程师编码', 'engineer coding'),
    # subaru/ssm-install-error.html
    ('能', 'can'),
    ('大于', 'greater than'),
    ('发行', 'release'),
    ('半', 'half'),
    ('然会报', 'will report'),
    ('候', 'when'),
    ('来临', 'arrives'),
    ('更改', 'change'),
    ('可以恢复过来', 'can recover'),
    ('间设定范围', 'time setting range'),
    # deere/e240lc-diag.html
    ('必须升级', 'must upgrade'),
    ('必须升级至', 'must upgrade to'),
    ('登陆', 'login'),
    ('已有', 'already have'),
    ('主页中', 'on home page'),
    ('故障码', 'fault code'),
    ('显示读取', 'display read'),
    ('流', 'data stream'),
    ('读数', 'readings'),
    ('流界面', 'data stream interface'),
    ('左侧', 'left side'),
    ('需要读取', 'need to read'),
    ('显示扫描', 'display scan'),
    ('阀学习值复', 'valve learning value reset'),
    ('学习值复', 'learning value reset'),
    # deere/index.html
    ('迪尔', 'Deere'),
    ('创办', 'founded'),
    ('美国迪尔', 'John Deere USA'),
    ('生产农业', 'manufactures agricultural'),
    ('建筑', 'construction'),
    ('森林机械', 'forestry machinery'),
    ('柴油引擎', 'diesel engines'),
    ('业务横跨', 'business spanning'),
    ('球所有农林地', 'global agricultural and forestry'),
    ('财富美国', 'Fortune USA'),
    ('财富世界', 'Fortune Global'),
    ('包括农业机械', 'including agricultural machinery'),
    ('工程机械', 'construction equipment'),
    ('林业机械', 'forestry equipment'),
    ('挖掘机', 'excavators'),
    # donet/hyper-remote.html
    ('电脑', 'computer'),
    ('好最', 'best'),
    ('及原厂', 'and OEM'),
    ('电脑有', 'computer has'),
    ('操作', 'operation'),
    # donet/intro.html
    ('微信', 'WeChat'),
    ('众', 'public'),
    ('即可实现故障', 'to achieve fault'),
    ('维修企业', 'repair company'),
    ('技术专家', 'technical experts'),
    ('互联互通', 'interconnection'),
    ('组成', 'composed of'),
    ('开放', 'open'),
    ('目前', 'currently'),
    ('面开放', 'is open for'),
    ('也已开放', 'also opened'),
    # donet/legacy-remote.html
    ('本文档介绍', 'this document introduces'),
    ('外接', 'external'),
    ('准备阶段', 'preparation stage'),
    ('分别按照以下', 'follow the respective'),
    # guide/connection.html
    ('接', 'connect'),
    ('启动正常', 'normal startup'),
    ('选中', 'select'),
    ('中可以看', 'can see in'),
    ('网卡', 'network adapter'),
    ('器中看', 'seen in'),
    ('只适', 'only for'),
    ('串口', 'serial port'),
    ('此', 'this'),
    ('无需', 'no need'),
    ('按照以上', 'following the above'),
    ('能正确显示', 'correctly display'),
    ('名称', 'name'),
    ('则', 'then'),
    ('已正确', 'already correctly'),
    ('上电脑', 'connect to computer'),
    ('识别所有', 'recognize all'),
    ('一般无需', 'generally no need'),
    # guide/device-ip-change.html
    ('相当于一', 'equivalent to a'),
    ('本身', 'itself'),
    ('远程', 'remote'),
    ('需要', 'need'),
    ('用户', 'user'),
    ('由器', 'router'),
    ('某些情况下', 'in some cases'),
    ('可能相同产生冲突', 'may conflict'),
    ('请先连正确', 'first connect correctly'),
    ('浏览器', 'browser'),
    ('登录', 'login'),
    ('其他', 'other'),
    ('也需要', 'also need'),
    # guide/diagnosis.html
    ('必须条件', 'prerequisites'),
    ('必须包含有效', 'must contain valid'),
    ('至电脑', 'to computer'),
    ('可联网', 'internet access'),
    ('版权属于其所有者', 'copyright belongs to respective owners'),
    ('查看可用', 'view available'),
    ('卡', 'card'),
    ('单击', 'click'),
    ('显示已', 'shows'),
    ('可用', 'available'),
    ('升级', 'upgrade'),
    ('持续', 'continuously'),
    ('请始终保持最', 'always keep latest'),
    ('当某款', 'when a'),
    ('其右上角会显示', 'upper right corner will show'),
    ('详情', 'details'),
    ('恢复', 'restore'),
    ('原始', 'original'),
    ('原厂', 'OEM'),
    # guide/faq.html
    ('找', 'find'),
    ('发现有', 'found'),
    ('而', 'while'),
    ('没', 'no'),
    ('还', 'also'),
    ('没连上', 'not connected'),
    ('计算机', 'computer'),
    ('看看', 'check'),
    ('里', 'in'),
    ('否异常', 'if abnormal'),
    ('异常请', 'if abnormal please'),
    ('内', 'within'),
    ('就可以了', 'that should work'),
    ('都没找', 'not found'),
    ('请看电脑', 'check computer'),
    ('否有', 'if there is'),
    ('信', 'signal'),
    ('没有话', 'if not'),
    ('返修', 'return for repair'),
    ('没找', 'not found'),
    ('这', 'this'),
    ('别电脑', 'other computer'),
    ('册过', 'registered'),
    ('拷贝硬盘', 'copy hard drive'),
    ('完整', 'complete'),
    ('重拷硬盘', 're-copy hard drive'),
    ('测', 'test'),
    ('了车', 'connected vehicle'),
    ('请让客户查看他', 'ask customer to check their'),
    ('破解', 'crack/patch'),
    ('家庭', 'home'),
    ('红框', 'red box'),
    ('击网卡', 'click network adapter'),
    ('点属性', 'click properties'),
    ('手动改', 'manually change'),
    ('按上面', 'follow above'),
    ('调整', 'adjust'),
    ('则更换电脑', 'replace computer'),
    ('再试', 'try again'),
    # guide/firmware.html
    ('标记', 'mark'),
    ('弹出', 'pop-up'),
    ('话框', 'dialog'),
    ('话框中勾选需要', 'check required in dialog'),
    ('恢复', 'recover'),
    ('秒', 'seconds'),
    ('没有听', 'if no'),
    ('第二次蜂鸣器', 'second beep'),
    ('哔哔', 'beep'),
    ('声', 'sound'),
    ('恢', 'restore'),
    ('复', 'recovery'),
    # guide/license.html
    ('列表', 'list'),
    ('此项', 'this item'),
    ('受限', 'restricted'),
    ('可更改', 'can be changed'),
    ('只', 'only'),
    ('运行', 'run'),
    ('管理', 'manage'),
    ('可看', 'can see'),
    ('必须定期', 'must periodically'),
    ('超过', 'exceeding'),
    ('天未', 'days without'),
    ('会过期', 'will expire'),
    ('会影响', 'will affect'),
    ('需要电脑', 'requires computer'),
    ('互联网', 'internet'),
    ('间隔', 'interval'),
    ('小', 'small'),
    ('可手动', 'can manually'),
    ('需', 'need'),
    ('可以联系经销商购买', 'contact dealer to purchase'),
    ('申请', 'apply'),
    ('需要提供以下', 'need to provide the following'),
    ('购买', 'purchase'),
    ('相应原厂', 'corresponding OEM'),
    ('之', 'of'),
    # guide/quickstart.html
    ('自由', 'freely'),
    ('需要原厂', 'OEM driver needed'),
    # product/index.html
    ('专用', 'dedicated'),
    ('性能', 'performance'),
    ('引', 'lead'),
    ('切换', 'switch'),
    ('智能切换', 'smart switching'),
    ('可切换', 'switchable'),
    ('定义两种', 'define two'),
    ('分配', 'allocate'),
    # product/vcx-doip.html
    ('高速', 'high-speed'),
    ('具备强大', 'with powerful'),
    ('性', 'capability'),
    ('最佳', 'best'),
    ('各大原厂', 'major OEM manufacturers'),
    ('保持同步', 'stay synchronized'),
    ('面', 'coverage'),
    ('实现世界主要', 'supporting major world'),
    ('可替代众多昂贵', 'replacing many expensive'),
    ('各种高级', 'various advanced'),
    ('设计', 'design'),
    ('高性能', 'high-performance'),
    ('核', 'core'),
    ('协同', 'cooperative'),
    ('协同', 'cooperative'),
    ('实现多', 'enable multiple'),
    ('发', 'channels'),
    ('创', 'innovative'),
    ('传统总线', 'traditional bus'),
    ('映射', 'mapping'),
    ('实现', 'achieve'),
    ('灵活易用', 'flexible and easy to use'),
    ('采用', 'using'),
    ('防反插加固设计', 'anti-reverse reinforced design'),
    ('稳定可靠', 'stable and reliable'),
    ('汽车', 'automotive'),
    ('重型', 'heavy-duty'),
    ('柴油', 'diesel'),
    ('金属', 'metal'),
    ('橡胶坚固设计能', 'robust rubber and metal design'),
    ('各种恶劣环境', 'harsh environments'),
    ('满足四大汽车工业', 'meets four automotive industry'),
    ('更换', 'replace'),
    ('扩展', 'expand'),
    ('铝金属', 'aluminum'),
    ('常亮', 'solid/always on'),
    ('闪烁', 'flashing'),
    ('传统', 'traditional'),
    ('屏蔽', 'shielded'),
    ('光盘', 'CD/DVD'),
    # product/vcx-fd.html remaining
    ('特殊', 'special'),
    ('一键', 'one-click'),
    ('快速接入', 'quick connect'),
    ('按键', 'button'),
    ('键', 'key'),
    ('长按', 'long press'),
    ('超级远程', 'hyper remote'),
    ('欧盟', 'EU'),
    ('美国', 'US'),
    ('呼吸闪烁', 'breathing flash'),
    ('故障', 'fault'),
    ('绿色闪烁', 'green flash'),
    ('绿色', 'green'),
    ('慢速闪烁', 'slow flash'),
    ('网口', 'network port'),
    # product/vcx-nano.html
    ('大多数', 'most'),
    ('设计紧凑', 'compact design'),
    ('一超高性价比', 'high value-for-money'),
    ('被', 'used by'),
    ('制造商广泛', 'widely by manufacturers'),
    ('它还', 'it also'),
    ('第三方', 'third-party'),
    ('替代昂贵', 'replace expensive'),
    ('别', 'different'),
    ('提供', 'provide'),
    ('搭载高速', 'equipped with high-speed'),
    ('一高性能', 'a high-performance'),
    ('大', 'large'),
    ('化', 'optimization'),
    ('原厂私有', 'OEM proprietary'),
    ('最多可', 'up to'),
    ('单线', 'single-wire'),
    ('多通道', 'multi-channel'),
    ('电压输出', 'voltage output'),
    ('紧凑型设计可直接', 'compact design can directly'),
    ('选配', 'optional'),
    ('长', 'length'),
    ('宽', 'width'),
    ('高', 'height'),
    ('塑胶', 'plastic'),
    # product/vcx-se.html remaining
    ('只需', 'only need'),
    ('联网即可实现原厂', 'internet connection for OEM'),
    ('可一键', 'one-click'),
    ('超高集成度', 'ultra-high integration'),
    ('便携式设计可即插即用', 'portable plug-and-play design'),
    ('加固设计', 'reinforced design'),
    ('可稳定插拔', 'stable plug/unplug'),
    ('满足汽车工业', 'meets automotive industry'),
    ('延长', 'extend'),
    # release/update_doip.html
    ('引', 'support'),
    ('避免', 'avoid'),
    ('其他', 'other'),
    ('重构', 'refactor'),
    ('实体', 'entity'),
    ('服务', 'service'),
    ('异常中断', 'abnormal interrupt'),
    ('恢复可用', 'restore availability'),
    ('某些情况一直显示锁定', 'always shows locked in some cases'),
    ('可能出错', 'may error'),
    ('暂', 'temporarily'),
    ('出错', 'error'),
    ('内核', 'kernel'),
    ('前快速复', 'quick pre-recovery'),
    ('可配置映射', 'configurable mapping'),
    ('台进程', 'process instance'),
    ('长', 'long'),
    ('间', 'period'),
    ('环保', 'eco-friendly'),
    ('实体传输通道', 'physical transmission channel'),
    ('读码命令', 'read code command'),
    ('否定应答', 'negative response'),
    ('某些情况', 'some cases'),
    ('能读取', 'can read'),
    ('未发送', 'not sent'),
    ('触发消息', 'trigger message'),
    ('否定应答处理', 'negative response handling'),
    ('卡住', 'stuck'),
    ('右', 'right'),
    ('座显示屏', 'seat display'),
    ('调试', 'debug'),
    ('端统一日志', 'unified log'),
    ('径', 'path'),
    ('老', 'old'),
    ('需要运行切换', 'need to run switch'),
    ('服务长', 'service long'),
    ('间运行', 'period running'),
    # drive-update.html
    ('更新时间', 'Update Date'),
    ('解决了小问题', 'Fixed minor issues'),
    ('通用', 'GM'),
    ('本田', 'Honda'),
    # donet/intro.html
    ('案例', 'cases'),
]

ZH2_PT = [
    ('通用', 'GM'),
    ('本田', 'Honda'),
    ('电控', 'controlo electrónico'),
    ('中读取故障码', 'ler código de falha de'),
    ('显示方向盘', 'mostrar volante'),
    ('置传感器', 'sensor de posição'),
    ('信', 'sinal'),
    ('可靠', 'fiável'),
    ('属偶发性故障', 'falha intermitente'),
    ('方向盘', 'volante'),
    ('角度传感器', 'sensor de ângulo'),
    ('电压', 'tensão'),
    ('线故障', 'falha no cabo'),
    ('故障码', 'código de falha'),
    ('由蓄电池所至', 'causado pela bateria'),
    ('没有损坏', 'sem danos'),
    ('方向盘角度传感器', 'sensor de ângulo de direção'),
    ('校零', 'calibração zero'),
    ('编码', 'codificação'),
    ('利用', 'usar'),
    ('自', 'auto'),
    ('基本设定', 'definições básicas'),
    ('具体', 'específico'),
    ('下', 'abaixo'),
    ('启动', 'iniciar'),
    ('方向盘向右', 'rodar volante para a direita'),
    ('再向左', 'depois para a esquerda'),
    ('停', 'parar'),
    ('中', 'centro'),
    ('刹车', 'travão'),
    ('读码', 'ler códigos'),
    ('清除故障码', 'limpar códigos de falha'),
    ('设置', 'definições'),
    ('码', 'código'),
    ('同', 'mesmo'),
    ('码可能', 'código pode ser'),
    ('正确则显示', 'correcto se mostrar'),
    ('登录', 'iniciar sessão'),
    ('登录码', 'código de acesso'),
    ('显示', 'mostrar'),
    ('登录码失败', 'código de acesso falhado'),
    ('主', 'principal'),
    ('基本调整', 'ajuste básico'),
    ('退出', 'sair'),
    ('某些', 'alguns'),
    ('上', 'acima'),
    ('用', 'usar'),
    ('代替了正确', 'substituindo o correcto'),
    ('制动', 'travão'),
    ('排气操作', 'operação de purga'),
    ('模组编码', 'codificação do módulo'),
    ('要', 'necessário'),
    ('才能', 'para poder'),
    ('线', 'cabo/linha'),
    ('操纵', 'operar'),
    ('检测', 'detectar'),
    ('图标', 'ícone'),
    ('此', 'este'),
    ('必须先用补丁破解', 'deve primeiro aplicar patch'),
    ('还要', 'também é necessário'),
    ('虚拟光驱加载', 'montar com unidade virtual'),
    ('资料', 'dados'),
    ('一般', 'geralmente'),
    ('会', 'irá'),
    ('识别', 'reconhecer'),
    ('模块', 'módulo'),
    ('此处', 'aqui'),
    ('硬盘', 'disco rígido'),
    ('比', 'do que'),
    ('成功', 'bem-sucedido'),
    ('变体编码', 'codificação de variante'),
    ('工业', 'industrial'),
    ('组', 'grupo'),
    ('快速', 'rapidamente'),
    ('连上电脑', 'ligar ao computador'),
    ('查看', 'verificar'),
    ('否最', 'se mais recente'),
    ('否正常', 'se normal'),
    ('一', 'um'),
    ('提示升级一律选', 'seleccionar sempre actualização quando pedido'),
    ('点', 'clique'),
    ('车扫描', 'scan do veículo'),
    ('扫描完', 'scan concluído'),
    ('点开', 'clique para abrir'),
    ('右边框框内查看', 'verificar no painel direito'),
    ('零件', 'peças'),
    ('准备好', 'pronto'),
    ('有些', 'alguns'),
    ('盘', 'disco'),
    ('夹内', 'na pasta'),
    ('没有话得', 'se não disponível, obter em'),
    ('官方服务器', 'servidor oficial'),
    ('应', 'deve'),
    ('选一起刷', 'seleccionar tudo para flash'),
    ('勾上所有', 'seleccionar tudo'),
    ('过程中', 'durante'),
    ('另一', 'outro'),
    ('都刷完', 'tudo actualizado'),
    ('进度条下方会有提示', 'barra de progresso indica conclusão'),
    ('第二代', 'segunda geração'),
    ('启用了', 'activado'),
    ('底盘编', 'código de chassis'),
    ('规则', 'regra'),
    ('它规定所有', 'especifica que todos'),
    ('底盘代', 'designação de chassis'),
    ('都以字母加三', 'todos usam letra mais três'),
    ('数字来表示', 'dígitos'),
    ('其中', 'onde'),
    ('代表', 'representa'),
    ('门车', 'porta'),
    ('代表跑车', 'representa desportivo'),
    ('代表旅行车', 'representa familiar'),
    ('代表越野车', 'representa SUV'),
    ('级', 'classe'),
    ('小型单厢车', 'hatchback compacto'),
    ('小型', 'compacto'),
    ('中级', 'médio porte'),
    ('高级', 'premium'),
    ('越野车', 'SUV'),
    ('多', 'multi'),
    ('厢式车', 'carrinha'),
    ('小型跑车', 'desportivo pequeno'),
    ('中型跑车', 'desportivo médio'),
    ('高级跑车', 'desportivo premium'),
    ('超级跑车', 'super desportivo'),
    ('底盘列表', 'lista de chassis'),
    ('款', 'modelo'),
    ('一款', 'um'),
    ('升直列', 'L em linha'),
    ('缸直列六缸顶置凸轮轴柴油', 'cilindros DOHC diesel'),
    ('它于', 'foi'),
    ('推出', 'lançado'),
    ('天然气', 'gás natural'),
    ('座', 'assento'),
    ('此款', 'este modelo'),
    ('圆形', 'redondo'),
    ('实际', 'real'),
    ('引', 'conduzir'),
    ('没有', 'sem'),
    ('接头情况下可以', 'conector pode'),
    ('线跳线', 'fio jumper'),
    ('配置', 'configurar'),
    ('由于', 'porque'),
    ('需要检测', 'necessário detectar'),
    ('还需要', 'também necessário'),
    ('此配置工具配置', 'configurar com esta ferramenta'),
    ('配置工具', 'ferramenta de configuração'),
    ('工业机组', 'motor industrial'),
    ('界面', 'interface'),
    ('提示', 'indicação'),
    ('插针', 'pino'),
    ('头', 'conector'),
    ('请配置', 'configurar'),
    ('结果', 'resultado'),
    ('发行', 'versão'),
    ('上编码', 'codificação em'),
    ('应用', 'aplicação'),
    ('允许用户禁用', 'permite ao utilizador desactivar'),
    ('激活其', 'activar'),
    ('以下', 'seguinte'),
    ('其中一些可以', 'alguns dos quais podem'),
    ('激活', 'activar'),
    ('禁用', 'desactivar'),
    ('锁定解锁声音', 'som de bloqueio/desbloqueio'),
    ('驾驶导航', 'navegação de condução'),
    ('驾驶', 'condução'),
    ('观看', 'ver'),
    ('输出', 'saída'),
    ('扭矩计', 'medidor de binário'),
    ('屏幕大屏幕启动延迟', 'atraso de arranque do ecrã grande'),
    ('语音识别', 'reconhecimento de voz'),
    ('设置三种', 'configurar três tipos de'),
    ('电话铃声', 'toque do telefone'),
    ('地址', 'endereço'),
    ('空调', 'ar condicionado'),
    ('室内循环记忆最', 'memória de circulação interior'),
    ('一次引擎', 'arranque do motor'),
    ('柱式电动', 'coluna eléctrica'),
    ('挡板按钮', 'botão da aba'),
    ('遥控钥匙', 'chave remota'),
    ('挡板', 'aba'),
    ('换档拨片', 'patilha de mudança'),
    ('小屏幕', 'ecrã pequeno'),
    ('大屏幕显示', 'ecrã grande'),
    ('垂直', 'vertical'),
    ('水平显示', 'horizontal'),
    ('驾驶员座椅', 'banco do condutor'),
    ('置', 'posição'),
    ('残疾人解开安', 'cinto de segurança para deficientes'),
    ('语音提示', 'indicação de voz'),
    ('乘客座', 'banco do passageiro'),
    ('行驶', 'condução'),
    ('交叉口', 'cruzamento'),
    ('远光灯', 'máximos'),
    ('控制', 'controlo'),
    ('天使眼睛', 'angel eyes'),
    ('起停', 'arranque/paragem'),
    ('情况下处于', 'em condições'),
    ('间同步', 'sincronizar'),
    ('盖', 'tampa'),
    ('来操作工程师', 'para operar modo de engenheiro'),
    ('连上电脑', 'ligar ao computador'),
    ('首先查看', 'primeiro verificar'),
    ('否最', 'se mais recente'),
    ('开关', 'interruptor'),
    ('就能读出', 'pode ler'),
    ('示', 'mostrado'),
    ('直接', 'directamente'),
    ('确定好', 'confirmar'),
    ('按图示操作', 'seguir diagrama'),
    ('编码也', 'codificação também'),
    ('这样读取', 'ler desta forma'),
    ('超级远程', 'super remoto'),
    ('连', 'ligar'),
    ('介绍', 'introdução'),
    ('能够读取', 'capaz de ler'),
    ('清除所有模块', 'limpar todos os módulos'),
    ('代码', 'códigos'),
    ('重置调整', 'repor ajustes'),
    ('查看实', 'ver valores reais'),
    ('所需只', 'requer apenas'),
    ('工程', 'engenharia'),
    ('生产', 'produção'),
    ('售', 'pós-venda'),
    ('案例', 'casos'),
    ('清除', 'limpar'),
    ('上传', 'enviar'),
    ('读取测量值', 'ler valores de medição'),
    ('输出控制', 'controlo de saída'),
    ('单', 'único'),
    ('变量校准', 'calibração de variável'),
    ('总线', 'barramento'),
    ('仿真', 'simulação'),
    ('车载', 'a bordo'),
    ('非车载集成', 'não integrado'),
    ('特定于客户', 'específico para cliente'),
    ('广泛', 'amplamente'),
    ('长期应用', 'aplicação de longa duração'),
    ('语言', 'idioma'),
    ('英语', 'Inglês'),
    ('德语', 'Alemão'),
    ('例', 'exemplo'),
    ('简单介绍', 'breve introdução'),
    ('连上', 'ligar'),
    ('首先要锁定', 'primeiro bloquear'),
    ('有两种', 'existem dois tipos de'),
    ('主页', 'página inicial'),
    ('所需', 'necessário'),
    ('即可', 'então'),
    ('故障码存储器', 'memória de códigos de falha'),
    ('读存储器', 'ler memória'),
    ('屏幕截图', 'captura de ecrã'),
    ('结束', 'fim'),
    ('运动型多', 'desportivo multi-purpose'),
    ('车', 'veículo'),
    ('旅行车', 'familiar'),
    ('专业版', 'Edição Profissional'),
    ('非家庭版', 'não-Home edition'),
    ('保证', 'garantir'),
    ('账户有管理员权限', 'conta com direitos de administrador'),
    ('运行库没有被正确', 'biblioteca de execução não correctamente'),
    ('运行库', 'biblioteca de execução'),
    ('已放入', 'já colocado em'),
    ('以及电子', 'e electrónico'),
    ('重', 're-'),
    ('包括但', 'incluindo mas'),
    ('限于', 'não limitado a'),
    ('提供访问所有本田', 'fornece acesso a todos Honda'),
    ('访问防盗', 'aceder ao imobilizador'),
    ('需要安', 'necessário'),
    ('专业人员', 'profissional'),
    ('订阅', 'subscrição'),
    ('安', 'instalar'),
    ('向', 'para'),
    ('册', 'registar'),
    ('充满了', 'repleto de'),
    ('特点', 'características'),
    ('给用户一布局有点熟悉传统', 'dá ao utilizador um layout familiar'),
    ('很长一段', 'durante muito'),
    ('间里很好地', 'tempo serviu bem'),
    ('了我们', 'a nós'),
    ('经过', 'após'),
    ('实践', 'prática'),
    ('一代工具被设计', 'a ferramenta da geração anterior foi concebida'),
    ('一代', 'geração'),
    ('所有完整', 'todas as completas'),
    ('变化', 'alterações'),
    ('要求', 'requisitos'),
    ('内', 'dentro'),
    ('要操作车款', 'para modelos mais antigos'),
    ('分', 'dividido em'),
    ('老款', 'mais antigo'),
    ('车款', 'modelo'),
    ('里', 'em'),
    ('即可换成工程师', 'mudar para modo de engenheiro'),
    ('同样操作选', 'mesma operação para seleccionar'),
    ('换回', 'voltar'),
    ('控制模块', 'módulo de controlo'),
    ('会发现', 'irá descobrir'),
    ('控制模块名字变', 'o nome do módulo de controlo muda para'),
    ('德文', 'Alemão'),
    ('多了开发', 'com desenvolvimento'),
    ('可', 'pode'),
    ('工程师编码', 'codificação de engenheiro'),
    ('能', 'pode'),
    ('大于', 'maior que'),
    ('半', 'metade'),
    ('然会报', 'irá reportar'),
    ('候', 'quando'),
    ('来临', 'chega'),
    ('更改', 'alterar'),
    ('可以恢复过来', 'pode recuperar'),
    ('间设定范围', 'intervalo de tempo'),
    ('必须升级', 'deve actualizar'),
    ('必须升级至', 'deve actualizar para'),
    ('登陆', 'iniciar sessão'),
    ('已有', 'já tem'),
    ('主页中', 'na página inicial'),
    ('故障码', 'código de falha'),
    ('显示读取', 'mostrar leitura'),
    ('流', 'fluxo de dados'),
    ('读数', 'leituras'),
    ('流界面', 'interface de fluxo de dados'),
    ('左侧', 'lado esquerdo'),
    ('需要读取', 'necessário ler'),
    ('显示扫描', 'mostrar scan'),
    ('阀学习值复', 'repor valor de aprendizagem da válvula'),
    ('学习值复', 'repor valor de aprendizagem'),
    ('迪尔', 'Deere'),
    ('创办', 'fundada'),
    ('美国迪尔', 'John Deere EUA'),
    ('生产农业', 'produz agricultura'),
    ('建筑', 'construção'),
    ('森林机械', 'maquinaria florestal'),
    ('柴油引擎', 'motores diesel'),
    ('业务横跨', 'negócio abrangendo'),
    ('球所有农林地', 'toda a terra agrícola e florestal global'),
    ('财富美国', 'Fortune EUA'),
    ('财富世界', 'Fortune Global'),
    ('包括农业机械', 'incluindo maquinaria agrícola'),
    ('工程机械', 'equipamento de construção'),
    ('林业机械', 'equipamento florestal'),
    ('挖掘机', 'escavadoras'),
    ('电脑', 'computador'),
    ('好最', 'melhor'),
    ('及原厂', 'e OEM'),
    ('电脑有', 'computador tem'),
    ('操作', 'operação'),
    ('微信', 'WeChat'),
    ('众', 'público'),
    ('即可实现故障', 'para realizar falhas'),
    ('维修企业', 'empresa de reparação'),
    ('技术专家', 'especialistas técnicos'),
    ('互联互通', 'interligação'),
    ('组成', 'composto por'),
    ('开放', 'aberto'),
    ('目前', 'actualmente'),
    ('面开放', 'está aberto para'),
    ('也已开放', 'também aberto'),
    ('本文档介绍', 'este documento apresenta'),
    ('外接', 'externo'),
    ('准备阶段', 'fase de preparação'),
    ('分别按照以下', 'seguir respectivamente'),
    ('接', 'ligar'),
    ('启动正常', 'arranque normal'),
    ('选中', 'seleccionar'),
    ('中可以看', 'pode ver em'),
    ('网卡', 'placa de rede'),
    ('器中看', 'ver em'),
    ('只适', 'apenas para'),
    ('串口', 'porta série'),
    ('无需', 'não necessário'),
    ('按照以上', 'seguindo o acima'),
    ('能正确显示', 'mostrar correctamente'),
    ('名称', 'nome'),
    ('则', 'então'),
    ('已正确', 'já correctamente'),
    ('上电脑', 'ligar ao computador'),
    ('识别所有', 'reconhecer todos'),
    ('一般无需', 'geralmente não necessário'),
    ('相当于一', 'equivalente a um'),
    ('本身', 'em si'),
    ('需要', 'necessário'),
    ('用户', 'utilizador'),
    ('由器', 'router'),
    ('某些情况下', 'em alguns casos'),
    ('可能相同产生冲突', 'pode criar conflito'),
    ('请先连正确', 'primeiro ligar correctamente'),
    ('浏览器', 'navegador'),
    ('其他', 'outro'),
    ('也需要', 'também necessário'),
    ('必须条件', 'pré-requisitos'),
    ('必须包含有效', 'deve conter válido'),
    ('至电脑', 'ao computador'),
    ('可联网', 'acesso à internet'),
    ('版权属于其所有者', 'direitos de autor pertencem aos respectivos proprietários'),
    ('查看可用', 'ver disponível'),
    ('卡', 'cartão'),
    ('单击', 'clique'),
    ('显示已', 'mostra'),
    ('可用', 'disponível'),
    ('升级', 'actualizar'),
    ('持续', 'continuamente'),
    ('请始终保持最', 'manter sempre a versão mais recente'),
    ('当某款', 'quando um'),
    ('其右上角会显示', 'canto superior direito mostra'),
    ('详情', 'detalhes'),
    ('恢复', 'restaurar'),
    ('原始', 'original'),
    ('原厂', 'OEM'),
    ('找', 'encontrar'),
    ('发现有', 'encontrado'),
    ('而', 'enquanto'),
    ('没', 'sem'),
    ('还', 'também'),
    ('没连上', 'não ligado'),
    ('计算机', 'computador'),
    ('看看', 'verificar'),
    ('里', 'em'),
    ('否异常', 'se anormal'),
    ('异常请', 'se anormal por favor'),
    ('内', 'dentro'),
    ('就可以了', 'deve funcionar'),
    ('都没找', 'não encontrado'),
    ('请看电脑', 'verificar computador'),
    ('否有', 'se existe'),
    ('没有话', 'se não'),
    ('返修', 'devolver para reparação'),
    ('没找', 'não encontrado'),
    ('别电脑', 'outro computador'),
    ('册过', 'registado'),
    ('拷贝硬盘', 'copiar disco rígido'),
    ('完整', 'completo'),
    ('重拷硬盘', 're-copiar disco rígido'),
    ('测', 'testar'),
    ('了车', 'veículo ligado'),
    ('请让客户查看他', 'pedir ao cliente para verificar'),
    ('破解', 'patch/crack'),
    ('家庭', 'Home edition'),
    ('红框', 'caixa vermelha'),
    ('击网卡', 'clique na placa de rede'),
    ('点属性', 'clique em propriedades'),
    ('手动改', 'alterar manualmente'),
    ('按上面', 'seguir acima'),
    ('调整', 'ajustar'),
    ('则更换电脑', 'substituir computador'),
    ('再试', 'tentar novamente'),
    ('标记', 'marcar'),
    ('弹出', 'pop-up'),
    ('话框', 'caixa de diálogo'),
    ('话框中勾选需要', 'seleccionar necessário na caixa de diálogo'),
    ('秒', 'segundos'),
    ('没有听', 'se não ouvir'),
    ('第二次蜂鸣器', 'segundo bipe'),
    ('哔哔', 'bipe'),
    ('声', 'som'),
    ('恢', 'restaurar'),
    ('复', 'recuperar'),
    ('列表', 'lista'),
    ('此项', 'este item'),
    ('受限', 'limitado'),
    ('可更改', 'pode ser alterado'),
    ('只', 'apenas'),
    ('运行', 'executar'),
    ('管理', 'gerir'),
    ('可看', 'pode ver'),
    ('必须定期', 'deve periodicamente'),
    ('超过', 'excedendo'),
    ('天未', 'dias sem'),
    ('会过期', 'irá expirar'),
    ('会影响', 'irá afectar'),
    ('需要电脑', 'requer computador'),
    ('互联网', 'internet'),
    ('间隔', 'intervalo'),
    ('小', 'pequeno'),
    ('可手动', 'pode manualmente'),
    ('需', 'necessário'),
    ('可以联系经销商购买', 'contactar revendedor para comprar'),
    ('申请', 'solicitar'),
    ('需要提供以下', 'necessário fornecer o seguinte'),
    ('购买', 'comprar'),
    ('相应原厂', 'OEM correspondente'),
    ('之', 'de'),
    ('自由', 'livremente'),
    ('需要原厂', 'driver OEM necessário'),
    ('专用', 'dedicado'),
    ('性能', 'desempenho'),
    ('引', 'conduzir'),
    ('切换', 'comutar'),
    ('智能切换', 'comutação inteligente'),
    ('可切换', 'comutável'),
    ('定义两种', 'definir dois'),
    ('分配', 'alocar'),
    ('高速', 'alta velocidade'),
    ('具备强大', 'com poderoso'),
    ('性', 'capacidade'),
    ('最佳', 'melhor'),
    ('各大原厂', 'principais fabricantes OEM'),
    ('保持同步', 'manter sincronizado'),
    ('面', 'cobertura'),
    ('实现世界主要', 'suportando os principais mundiais'),
    ('可替代众多昂贵', 'substituindo muitos caros'),
    ('各种高级', 'vários avançados'),
    ('设计', 'design'),
    ('高性能', 'alto desempenho'),
    ('核', 'núcleo'),
    ('协同', 'cooperativo'),
    ('实现多', 'permitir múltiplos'),
    ('发', 'canais'),
    ('创', 'inovador'),
    ('传统总线', 'barramento tradicional'),
    ('映射', 'mapeamento'),
    ('实现', 'alcançar'),
    ('灵活易用', 'flexível e fácil de usar'),
    ('采用', 'utilizando'),
    ('防反插加固设计', 'design anti-inversão reforçado'),
    ('稳定可靠', 'estável e fiável'),
    ('汽车', 'automóvel'),
    ('重型', 'pesado'),
    ('柴油', 'diesel'),
    ('金属', 'metal'),
    ('橡胶坚固设计能', 'design robusto de borracha e metal'),
    ('各种恶劣环境', 'ambientes adversos'),
    ('满足四大汽车工业', 'cumpre quatro padrões da indústria automóvel'),
    ('更换', 'substituir'),
    ('扩展', 'expandir'),
    ('铝金属', 'alumínio'),
    ('常亮', 'luz constante'),
    ('闪烁', 'a piscar'),
    ('传统', 'tradicional'),
    ('屏蔽', 'blindado'),
    ('光盘', 'CD/DVD'),
    ('特殊', 'especial'),
    ('一键', 'um clique'),
    ('快速接入', 'ligação rápida'),
    ('按键', 'botão'),
    ('键', 'tecla'),
    ('长按', 'pressão longa'),
    ('超级远程', 'super remoto'),
    ('欧盟', 'UE'),
    ('美国', 'EUA'),
    ('呼吸闪烁', 'piscar de respiração'),
    ('故障', 'falha'),
    ('绿色闪烁', 'piscar verde'),
    ('绿色', 'verde'),
    ('慢速闪烁', 'piscar lento'),
    ('网口', 'porta de rede'),
    ('大多数', 'maioria'),
    ('设计紧凑', 'design compacto'),
    ('一超高性价比', 'alta relação qualidade-preço'),
    ('被', 'utilizado por'),
    ('制造商广泛', 'amplamente por fabricantes'),
    ('它还', 'também'),
    ('第三方', 'terceiros'),
    ('替代昂贵', 'substituir caros'),
    ('别', 'diferentes'),
    ('提供', 'fornecer'),
    ('搭载高速', 'equipado com alta velocidade'),
    ('一高性能', 'um de alto desempenho'),
    ('大', 'grande'),
    ('化', 'optimização'),
    ('原厂私有', 'OEM proprietário'),
    ('最多可', 'até'),
    ('单线', 'fio único'),
    ('多通道', 'multi-canal'),
    ('电压输出', 'saída de tensão'),
    ('紧凑型设计可直接', 'design compacto pode directamente'),
    ('选配', 'opcional'),
    ('长', 'comprimento'),
    ('宽', 'largura'),
    ('高', 'altura'),
    ('塑胶', 'plástico'),
    ('只需', 'apenas necessário'),
    ('联网即可实现原厂', 'ligação à internet para OEM'),
    ('可一键', 'um clique'),
    ('超高集成度', 'ultra-alta integração'),
    ('便携式设计可即插即用', 'design portátil plug-and-play'),
    ('加固设计', 'design reforçado'),
    ('可稳定插拔', 'inserção/remoção estável'),
    ('满足汽车工业', 'cumpre padrões da indústria automóvel'),
    ('延长', 'estender'),
    ('引', 'suporte'),
    ('避免', 'evitar'),
    ('其他', 'outro'),
    ('重构', 'refazer'),
    ('实体', 'entidade'),
    ('服务', 'serviço'),
    ('异常中断', 'interrupção anormal'),
    ('恢复可用', 'restaurar disponibilidade'),
    ('某些情况一直显示锁定', 'sempre mostra bloqueado em alguns casos'),
    ('可能出错', 'pode dar erro'),
    ('暂', 'temporariamente'),
    ('出错', 'erro'),
    ('内核', 'kernel'),
    ('前快速复', 'pré-recuperação rápida'),
    ('可配置映射', 'mapeamento configurável'),
    ('台进程', 'instância de processo'),
    ('长', 'longo'),
    ('间', 'período'),
    ('环保', 'eco-friendly'),
    ('实体传输通道', 'canal de transmissão físico'),
    ('读码命令', 'comando de leitura de código'),
    ('否定应答', 'resposta negativa'),
    ('某些情况', 'alguns casos'),
    ('能读取', 'pode ler'),
    ('未发送', 'não enviado'),
    ('触发消息', 'mensagem de disparo'),
    ('否定应答处理', 'tratamento de resposta negativa'),
    ('卡住', 'bloqueado'),
    ('右', 'direita'),
    ('座显示屏', 'ecrã do banco'),
    ('调试', 'depuração'),
    ('端统一日志', 'log unificado'),
    ('径', 'caminho'),
    ('老', 'antigo'),
    ('需要运行切换', 'necessário executar comutação'),
    ('服务长', 'serviço longo'),
    ('间运行', 'execução de período'),
]

def translate_chinese_pass2(text, translations):
    """Replace Chinese strings using provided translation list."""
    for zh, target in translations:
        text = text.replace(zh, target)
    return text

# Process all files
BASE = Path('D:/Tutorials/m-auto.online/vci-help')
import re
zh_pattern = re.compile(r'[\u4e00-\u9fff]')

files = []
for root, dirs, fnames in os.walk(BASE):
    dirs[:] = [d for d in dirs if d not in ['_raw', 'assets']]
    for f in fnames:
        if f.endswith('.html'):
            files.append(Path(root) / f)

changed = 0
for fp in files:
    is_pt = '\\pt\\' in str(fp) or '/pt/' in str(fp)
    is_en = '\\en\\' in str(fp) or '/en/' in str(fp)
    try:
        content = fp.read_text(encoding='utf-8-sig')
    except Exception as e:
        continue
    if not zh_pattern.search(content):
        continue
    original = content
    if is_pt:
        content = translate_chinese_pass2(content, ZH2_PT)
    else:
        content = translate_chinese_pass2(content, ZH2_EN)
    if content != original:
        fp.write_text(content, encoding='utf-8')
        changed += 1

print(f'Pass 2: {changed} files updated')

# Final scan
remaining = []
for fp in files:
    try:
        content = fp.read_text(encoding='utf-8-sig')
        matches = re.findall(r'[\u4e00-\u9fff]+', content)
        if matches:
            remaining.append((str(fp).replace(str(BASE)+'\\', '').replace(str(BASE)+'/', ''), list(dict.fromkeys(matches))))
    except: pass

with open(str(BASE / '_remaining_chinese_pass2.txt'), 'w', encoding='utf-8') as out:
    out.write(f'Files with remaining Chinese after pass 2: {len(remaining)}\n\n')
    for fp, chars in remaining:
        out.write(f'{fp}\n')
        for c in chars:
            out.write(f'  {c}\n')
        out.write('\n')

print(f'After pass 2: {len(remaining)} files still have Chinese')
